version: '3'

services:
  web:
    image: nginx:1.25
    container_name: web_server
    ports:
      - "8080:80"
    networks:
      - webnet
      - dbnet
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_server
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    expose:
      - "5432"  # Internal only; not exposed to host
    networks:
      - dbnet

networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge

